# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_publick',
            field=models.BooleanField(default=False),
        ),
    ]
